name: Run Checks

on:
  push:
    branches: [development, feature/*, hotfix/*]

permissions:
  checks: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger App Check
        uses: autonoma-sandbox/github-app-check-trigger@v8
        with:
          test-id: "cm8vxp4d100a9ku81laaobrnh"
          check-name: "Testing something"
        env:
          GITHUB_TOKEN: ${{ github.token }}
