name: Run Checks

on:
  pull_request:
    branches: [main, staging]
  push:
    branches: [development, feature/*, hotfix/*]

permissions:
  # Required for creating check runs
  checks: write
  # Required to read repository content
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger App Check
        uses: autonoma-sandbox/github-app-check-trigger@v2
        with:
          check-name: "Branch Validation"
        env:
          GITHUB_TOKEN: ${{ github.token }}
