name: Run Checks

on:
  push:
    branches: [development, feature/*, hotfix/*]

permissions:
  checks: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger App Check2
        uses: autonoma-sandbox/github-app-check-trigger@v6
        with:
          test-id: "cm8heqewe000164i9by1dsqrf"
          check-name: "Testing something"
        env:
          GITHUB_TOKEN: ${{ github.token }}
