name: Run Checks

on:
  pull_request:
    branches: [main, staging]
  push:
    branches: [development, feature/*, hotfix/*]

permissions:
  # Required for creating check runs
  checks: write
  # Required to read repository content
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger App Check
        uses: autonoma-sandbox/github-app-check-trigger@v3
        with:
          test-id: "cm8heqewe000164i9by1dsqrf"
        env:
          GITHUB_TOKEN: ${{ github.token }}
